### ISSUE TITLE
[1.12] Crashes looking for options.txt

### ISSUE THREAD

**Issue by savosdarkran** [Wyn-Price/Sounds-Extended#1]
crashes looking for options.txt

https://pastebin.com/VwmkpwGY

**Comment by Wyn-Price** [comment]
Didn't realize this would be an issue. I know how to do a easy fix for it and it'll be fixed in the massive update happening tonight. If you play on the previous version, there isn't anything different apart from the music off function

**Comment by savosdarkran** [comment]
I'll await the update.  Thanks for your help and the mod :D

**Comment by Wyn-Price** [comment]
If you remove the mod, load up Minecraft then load up Minecraft with the mod installed, does it still crash?

**Comment by savosdarkran** [comment]
I tried that before posting the pastebin.  I will double check the path and if the file exists there, or where it is when I get home and update.

**Comment by Wyn-Price** [comment]
Ok, because if it crashes when the file is there we have a problem

**Comment by savosdarkran** [comment]
The file doesn't even exist.
![options](https://user-images.githubusercontent.com/26523998/27345481-da2c358c-55b7-11e7-8ea8-4286a1d10b0a.PNG)

**Comment by Wyn-Price** [comment]
It didnt load because the game crashed. Ive coded a fix for this but Im currently just pasting it across all versions. The fix should be in less than a minute or so

**Comment by Wyn-Price** [comment]
took a little longer than expected. The new huge release is not building and should be uploaded soon
![image](https://user-images.githubusercontent.com/15876682/27347766-a67aa912-55e9-11e7-81ad-0d27fdced70f.png)

**Comment by Wyn-Price** [comment]
the new huge release is not building and should be uploaded soon
