### ISSUE TITLE
[1.12] Exception on load

### ISSUE THREAD

**Issue by Symbai** [Wyn-Price/Sounds-Extended#2]
I just downloaded sounds extended-1.8.1-1.12.jar and got a crash on Minecraft start.

Forge: 14.21.1.2387

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Sounds Extended (sounds_extended)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

Full crash log: https://pastebin.com/ynnNw6CX

**Comment by noblereign** [comment]
Same error on 1.8.0-1.11.2

**Comment by Wyn-Price** [comment]
OK i know the error. My website just ran out and I need to renew it. This wont take long

**Comment by Wyn-Price** [comment]
OK ive placed the order for the renewal of the domain name, it should come through any minute and you can play

**Comment by Symbai** [comment]
So does this mean the mod needs a permanent internet connection to work?

**Comment by Wyn-Price** [comment]
no, as if it dosnt have a connection, it just moves on

**Comment by Wyn-Price** [comment]
wait it does...

**Comment by Wyn-Price** [comment]
OK im adding a feature to make it so it dosnt crash when you load it upwithout a internet connection right now. It should be online in 5 minutes

**Comment by Symbai** [comment]
Thank you for your fast responses and the fixes. I appreciate it a lot

**Comment by Wyn-Price** [comment]
its fine, I enjoy it
